# Generated by Django 6.0.4 on 2026-04-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='badge',
            field=models.CharField(choices=[('none', 'None'), ('verified_publisher', 'Verified Publisher'), ('sponsored_oss', 'Sponsored OSS')], default='none', max_length=30),
        ),
    ]
